[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
physics = { path = "../physics" }
ai = { path = "../ai" }
app = { path = "../app" }
infra = { path = "../infra" }
input = { path = "../input" }
rendering = { path = "../rendering" }
bevy = { workspace = true }
glam = { workspace = true }
rand = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
getrandom_02 = { workspace = true }
getrandom_03 = { workspace = true }
